[package]
name = "flux-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
array-init = "2.1"
lazy_static = "1.4.0"
# bitvec = "1.0"
# num-bigint = "0.4.3"
# num-rational = "0.4.1"
# num-traits = "0.2.15"
ordered-float = "3.4"
thiserror = "1.0"
