[package]
name = "flux-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
derive_more = "0.99.17"
enum-map = "2.6.2"
enumset = "1.1.2"
lazy_static = "1.4.0"
num = { version = "0.4.1", features = ["num-bigint"] }
ordered-float = "3.9.1"
paste = "1.0.14"
thiserror = "1.0.48"

[dev-dependencies]
notify = "6.1.1"
